In [3]:
import numpy as np
import pandas as pd

In [4]:
# Load the dataset
df = pd.read_csv(r"C:\Users\omhee\Downloads\Cardiovascular_Disease_Dataset (2).csv")
df

patientid  age  gender  chestpain  restingBP  serumcholestrol  \
0       103368   53       1          2        171                0   
1       119250   40       1          0         94              229   
2       119372   49       1          2        133              142   
3       132514   43       1          0        138              295   
4       146211   31       1          1        199                0   
..         ...  ...     ...        ...        ...              ...   
995    9949544   48       1          2        139              349   
996    9953423   47       1          3        143              258   
997    9965859   69       1          0        156              434   
998    9988507   45       1          1        186              417   
999    9990855   25       1          0        158              270   

     fastingbloodsugar  restingrelectro  maxheartrate  exerciseangia  oldpeak  \
0                    0                1           147              0      5.3   
1                    0                1           115              0      3.7   
2                    0                0           202              1      5.0   
3                    1                1           153              0      3.2   
4                    0                2           136              0      5.3   
..                 ...              ...           ...            ...      ...   
995                  0                2           183              1      5.6   
996                  1                1            98              1      5.7   
997                  1                0           196              0      1.4   
998                  0                1           117              1      5.9   
999                  0                0           143              1      4.7   

     slope  noofmajorvessels  target  
0        3                 3       1  
1        1                 1       0  
2        1                 0       0  
3        2                 2       1  
4        3                 2       1  
..     ...               ...     ...  
995      2                 2       1  
996      1                 0       0  
997      3                 1       1  
998      3                 2       1  
999      0                 0       0  

[1000 rows x 14 columns]

In [5]:
df.head()

patientid  age  gender  chestpain  restingBP  serumcholestrol  \
0     103368   53       1          2        171                0   
1     119250   40       1          0         94              229   
2     119372   49       1          2        133              142   
3     132514   43       1          0        138              295   
4     146211   31       1          1        199                0   

   fastingbloodsugar  restingrelectro  maxheartrate  exerciseangia  oldpeak  \
0                  0                1           147              0      5.3   
1                  0                1           115              0      3.7   
2                  0                0           202              1      5.0   
3                  1                1           153              0      3.2   
4                  0                2           136              0      5.3   

   slope  noofmajorvessels  target  
0      3                 3       1  
1      1                 1       0  
2      1                 0       0  
3      2                 2       1  
4      3                 2       1

In [6]:
df.shape

(1000, 14)

In [7]:
df.describe

<bound method NDFrame.describe of      patientid  age  gender  chestpain  restingBP  serumcholestrol  \
0       103368   53       1          2        171                0   
1       119250   40       1          0         94              229   
2       119372   49       1          2        133              142   
3       132514   43       1          0        138              295   
4       146211   31       1          1        199                0   
..         ...  ...     ...        ...        ...              ...   
995    9949544   48       1          2        139              349   
996    9953423   47       1          3        143              258   
997    9965859   69       1          0        156              434   
998    9988507   45       1          1        186              417   
999    9990855   25       1          0        158              270   

     fastingbloodsugar  restingrelectro  maxheartrate  exerciseangia  oldpeak  \
0                    0                1     

In [8]:
# Find the total number of rows
total_rows = df.shape[0]

# Print the result
print("Total Rows:", total_rows)

Total Rows: 1000


In [9]:
print("Column Information:")
print(df.info())

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   patientid          1000 non-null   int64  
 1   age                1000 non-null   int64  
 2   gender             1000 non-null   int64  
 3   chestpain          1000 non-null   int64  
 4   restingBP          1000 non-null   int64  
 5   serumcholestrol    1000 non-null   int64  
 6   fastingbloodsugar  1000 non-null   int64  
 7   restingrelectro    1000 non-null   int64  
 8   maxheartrate       1000 non-null   int64  
 9   exerciseangia      1000 non-null   int64  
 10  oldpeak            1000 non-null   float64
 11  slope              1000 non-null   int64  
 12  noofmajorvessels   1000 non-null   int64  
 13  target             1000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 109.5 KB
None


# DATA PREPROCESSING

In [10]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Read the dataset
df = pd.read_csv(r"C:\Users\omhee\Downloads\Cardiovascular_Disease_Dataset (2).csv")

# Convert 'gender' column to numerical values (if needed)
# Example: Convert 0 for female, 1 for male
df['gender'] = df['gender'].map({'female': 0, 'male': 1})

# Feature scaling for numerical columns
scaler = StandardScaler()
numerical_columns = ['age', 'restingBP', 'serumcholestrol', 'maxheartrate', 'oldpeak']
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# One-hot encode categorical variables (if needed)
df = pd.get_dummies(df, columns=['chestpain', 'restingrelectro'], prefix=['cp', 'relectro'])

# Explore the updated dataset
print("Updated dataset:\n", df.head())

Updated dataset:
    patientid       age  gender  restingBP  serumcholestrol  fastingbloodsugar  \
0     103368  0.210464     NaN   0.642833        -2.352717                  0   
1     119250 -0.517591     NaN  -1.928098        -0.622817                  0   
2     119372 -0.013553     NaN  -0.625938        -1.280028                  0   
3     132514 -0.349578     NaN  -0.458995        -0.124243                  1   
4     146211 -1.021629     NaN   1.577717        -2.352717                  0   

   maxheartrate  exerciseangia   oldpeak  slope  noofmajorvessels  target  \
0      0.044567              0  1.507245      3                 3       1   
1     -0.891840              0  0.576955      1                 1       0   
2      1.654017              1  1.332816      1                 0       0   
3      0.220143              0  0.286239      2                 2       1   
4     -0.277323              0  1.507245      3                 2       1   

   cp_0  cp_1  cp_2  cp_3  relec

In [11]:
df.columns

Index(['patientid', 'age', 'gender', 'restingBP', 'serumcholestrol',
       'fastingbloodsugar', 'maxheartrate', 'exerciseangia', 'oldpeak',
       'slope', 'noofmajorvessels', 'target', 'cp_0', 'cp_1', 'cp_2', 'cp_3',
       'relectro_0', 'relectro_1', 'relectro_2'],
      dtype='object')

In [12]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Separate features (X) and target variable (y)
X = df.drop(['patientid', 'target'], axis=1)
y = df['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the scaler
scaler = MinMaxScaler()

# Fit the scaler on your training data and transform both training and test data
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)

# Convert values to binary using a threshold (e.g., 0.5)
threshold = 0.5
X_train_binary = (X_train_normalized >= threshold).astype(int)
X_test_binary = (X_test_normalized >= threshold).astype(int)

# Print the binary data
print("X_train_binary:")
print(X_train_binary)

print("\nX_test_binary:")
print(X_test_binary)


X_train_binary:
[[0 0 1 ... 0 0 1]
 [1 0 0 ... 1 0 0]
 [1 0 1 ... 1 0 0]
 ...
 [0 0 1 ... 0 1 0]
 [1 0 1 ... 0 1 0]
 [1 0 0 ... 1 0 0]]

X_test_binary:
[[0 0 1 ... 0 1 0]
 [0 0 1 ... 1 0 0]
 [1 0 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 1 0 0]
 [1 0 0 ... 0 0 1]]


C:\Users\omhee\anaconda3\Lib\site-packages\sklearn\preprocessing\_data.py:479: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
C:\Users\omhee\anaconda3\Lib\site-packages\sklearn\preprocessing\_data.py:480: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


# CONFUSION MATRIX

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.impute import SimpleImputer

# Load your data (assuming it's stored in a DataFrame called df)
# Replace 'df' with the name of your DataFrame containing your data
# df = pd.read_csv('your_data.csv')

# Impute missing values
imputer = SimpleImputer(strategy='mean')  # You can choose a different strategy if needed
X_imputed = imputer.fit_transform(X)

# Separate features (X) and target variable (y)
X = df.drop(['patientid', 'target'], axis=1)
y = df['target']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

# Standardize features (optional but can be beneficial for some models)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create and train a Random Forest Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_train)

# Make predictions
y_pred = classifier.predict(X_test)

# Create a confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# Calculate and display accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")


C:\Users\omhee\anaconda3\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['gender']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


Confusion Matrix:
[[ 82   1]
 [  1 116]]
Accuracy: 99.00%


# RANDOM FOREST

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import time

# Record start time
start_time = time.time()

# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# Record end time
end_time = time.time()

# Display results and execution time
print(f'Random Forest Accuracy: {accuracy_rf*100:.2f}')
print(f'Execution time: {end_time - start_time:.2f} seconds')


Random Forest Accuracy: 98.50
Execution time: 0.54 seconds


# SUPPORT VETCOR MACHINE

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import time

# Load the dataset
df = pd.read_csv(r"C:\Users\omhee\Downloads\Cardiovascular_Disease_Dataset (2).csv")

# Split the dataset into features (X) and target variable (y)
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Record start time
start_time = time.time()

# Create and train the SVM model
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Record end time
end_time = time.time()

# Calculate accuracy
accuracy_svm = accuracy_score(y_test, y_pred)

# Display accuracy and execution time
print(f'Accuracy: {accuracy_svm*100:.4f}')
print(f'Execution time: {end_time - start_time:.4f} seconds')


Accuracy: 96.5000
Execution time: 0.0254 seconds


# XGBOOST 

In [16]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

# Assuming your dataframe is named 'df'
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Record start time
start_time = time.time()

# Initialize and train an XGBoost Classifier
clf = xgb.XGBClassifier(random_state=42)
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Record end time
end_time = time.time()

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)

# Display accuracy and execution time
print(f'Accuracy: {accuracy}')
print(f'Execution time: {end_time - start_time:.4f} seconds')


Accuracy: 0.97
Execution time: 0.1766 seconds


# LIGHTGBM

In [17]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import time

# Assuming 'X' is your feature matrix and 'y' is the target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define LightGBM parameters (you can adjust these based on your dataset)
params = {
    'objective': 'binary',
    'metric': 'binary_error',
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9
}

# Record start time
start_time = time.time()

# Create and train the LightGBM model
bst = lgb.train(params, lgb.Dataset(X_train, label=y_train), num_boost_round=100)

# Make predictions on the test set
y_pred = bst.predict(X_test, num_iteration=bst.best_iteration)
y_pred_binary = [1 if x >= 0.5 else 0 for x in y_pred]

# Record end time
end_time = time.time()

# Evaluate the model
print(f'Accuracy: {accuracy_score(y_test, y_pred_binary)}')
print(classification_report(y_test, y_pred_binary))

# Display execution time
print(f'Execution time: {end_time - start_time:.4f} seconds')


[LightGBM] [Info] Number of positive: 463, number of negative: 337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000758 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 845
[LightGBM] [Info] Number of data points in the train set: 800, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.578750 -> initscore=0.317644
[LightGBM] [Info] Start training from score 0.317644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[

# HYPER PARAMETER TUNED 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score
import time

# Split the dataset into features (X) and target variable (y)
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Define the Random Forest classifier
rf_classifier = RandomForestClassifier()

# Define the hyperparameter grid to search
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Record start time
start_time = time.time()

# Perform Grid Search with Cross-Validation
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best hyperparameters from the grid search
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train the Random Forest model with the best hyperparameters
best_rf_model = RandomForestClassifier(**best_params)
best_rf_model.fit(X_train, y_train)

# Record end time
end_time = time.time()

# Make predictions on the validation set
y_val_pred = best_rf_model.predict(X_val)

# Evaluate the performance on the validation set
accuracy = accuracy_score(y_val, y_val_pred)
print("Validation Accuracy:", accuracy)

# Display execution time
print(f'Execution time: {end_time - start_time:.4f} seconds')


# LSTM

In [19]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
import time

# Record start time
start_time = time.time()

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Reshape the data for LSTM
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))

# Build the LSTM model
model = Sequential()
model.add(LSTM(units=50, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=25, batch_size=32, validation_split=0.1)

# Make predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

# Record end time
end_time = time.time()

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

# Display execution time
print(f'Execution time: {end_time - start_time:.4f} seconds')





Epoch 1/25


23/23 [==============================] - 11s 75ms/step - loss: 0.6534 - accuracy: 0.7014 - val_loss: 0.6155 - val_accuracy: 0.8250
Epoch 2/25
23/23 [==============================] - 0s 10ms/step - loss: 0.5707 - accuracy: 0.8944 - val_loss: 0.5448 - val_accuracy: 0.8625
Epoch 3/25
23/23 [==============================] - 0s 13ms/step - loss: 0.4938 - accuracy: 0.9153 - val_loss: 0.4784 - val_accuracy: 0.8625
Epoch 4/25
23/23 [==============================] - 0s 14ms/step - loss: 0.4252 - accuracy: 0.9167 - val_loss: 0.4186 - val_accuracy: 0.8625
Epoch 5/25
23/23 [==============================] - 0s 7ms/step - loss: 0.3650 - accuracy: 0.9194 - val_loss: 0.3701 - val_accuracy: 0.8750
Epoch 6/25
23/23 [==============================] - 0s 8ms/step - loss: 0.3155 - accuracy: 0.9208 - val_loss: 0.3330 - val_accuracy: 0.8875
Epoch 7/25
23/23 [==============================] - 0s 8ms/step - loss: 0.2813 - accuracy: 0.9306 - val_loss: 0.3052 - val_accuracy: 0.8875
Epoch 8/25

# LSTM AND RNN COMBINE

In [20]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, Dense, Dropout

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Reshape the data for RNN and LSTM
X_train_rnn = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test_rnn = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

# Build the combined model
model = Sequential()
model.add(SimpleRNN(units=50, input_shape=(X_train_rnn.shape[1], X_train_rnn.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_rnn, y_train, epochs=75
          , batch_size=32, validation_split=0.1)

# Make predictions on the test set
y_pred_prob = model.predict(X_test_rnn)
y_pred = (y_pred_prob > 0.5).astype(int)

# Evaluate the performance on the test set
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


Epoch 1/75
23/23 [==============================] - 9s 88ms/step - loss: 0.5193 - accuracy: 0.7778 - val_loss: 0.4053 - val_accuracy: 0.8125
Epoch 2/75
23/23 [==============================] - 1s 24ms/step - loss: 0.3649 - accuracy: 0.8528 - val_loss: 0.3482 - val_accuracy: 0.8500
Epoch 3/75
23/23 [==============================] - 1s 25ms/step - loss: 0.3088 - accuracy: 0.8931 - val_loss: 0.3092 - val_accuracy: 0.9000
Epoch 4/75
23/23 [==============================] - 1s 25ms/step - loss: 0.2611 - accuracy: 0.9097 - val_loss: 0.2665 - val_accuracy: 0.9000
Epoch 5/75
23/23 [==============================] - 1s 24ms/step - loss: 0.2186 - accuracy: 0.9222 - val_loss: 0.2678 - val_accuracy: 0.9000
Epoch 6/75
23/23 [==============================] - 1s 23ms/step - loss: 0.1941 - accuracy: 0.9417 - val_loss: 0.2310 - val_accuracy: 0.9000
Epoch 7/75
23/23 [==============================] - 1s 24ms/step - loss: 0.1651 - accuracy: 0.9431 - val_loss: 0.2273 - val_accuracy: 0.9125
Epoch 8/75
23

In [24]:
# Importing necessary libraries
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

# Preprocessing: Splitting into features and target variable
X = df.drop(columns=['target'])  # Features
y = df['target']  # Target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initializing CatBoostClassifier
catboost_model = CatBoostClassifier()

# Measuring execution time
start_time = time.time()

# Training the model
catboost_model.fit(X_train, y_train, verbose=100)

# Calculating the training time
training_time = time.time() - start_time

# Making predictions
y_pred_train = catboost_model.predict(X_train)
y_pred_test = catboost_model.predict(X_test)

# Evaluating the model
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Training Time:", training_time, "seconds")


Learning rate set to 0.009366
0:	learn: 0.6765727	total: 182ms	remaining: 3m 1s
100:	learn: 0.1444773	total: 777ms	remaining: 6.92s
200:	learn: 0.0755701	total: 1.43s	remaining: 5.68s
300:	learn: 0.0507105	total: 2.07s	remaining: 4.81s
400:	learn: 0.0379202	total: 2.65s	remaining: 3.96s
500:	learn: 0.0295310	total: 3.23s	remaining: 3.21s
600:	learn: 0.0236648	total: 3.84s	remaining: 2.55s
700:	learn: 0.0193108	total: 4.44s	remaining: 1.9s
800:	learn: 0.0162409	total: 4.95s	remaining: 1.23s
900:	learn: 0.0140668	total: 5.5s	remaining: 605ms
999:	learn: 0.0125800	total: 6.07s	remaining: 0us
Train Accuracy: 1.0
Test Accuracy: 0.99
Training Time: 6.51301383972168 seconds


In [29]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import time


# Preprocessing: Splitting into features and target variable
X = df.drop(columns=['target'])  # Features
y = df['target']  # Target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initializing KNeighborsClassifier
knn_model = KNeighborsClassifier()

# Measuring execution time
start_time = time.time()

# Training the model
knn_model.fit(X_train, y_train)

# Calculating the training time
training_time = time.time() - start_time

# Making predictions
y_pred_train = knn_model.predict(X_train)
y_pred_test = knn_model.predict(X_test)

# Evaluating the model
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Training Time:", training_time, "seconds")


Train Accuracy: 0.675
Test Accuracy: 0.515
Training Time: 0.006153583526611328 seconds


In [35]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder


# Perform label encoding for categorical variables
label_encoder = LabelEncoder()
df['gender'] = label_encoder.fit_transform(df['gender'])
df['chestpain'] = label_encoder.fit_transform(df['chestpain'])

# You may need to encode other categorical variables if present in your dataset

# Display the encoded dataset
print(df)
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score


# Preprocessing: Splitting into features and target variable
X = df.drop(columns=['target'])  # Features
y = df['target']  # Target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initializing Gaussian Naive Bayes classifier
naive_bayes_model = GaussianNB()

# Training the model
naive_bayes_model.fit(X_train, y_train)

# Making predictions
y_pred_train = naive_bayes_model.predict(X_train)
y_pred_test = naive_bayes_model.predict(X_test)

# Evaluating the model
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)


     patientid  age  gender  chestpain  restingBP  serumcholestrol  \
0       103368   53       1          2        171                0   
1       119250   40       1          0         94              229   
2       119372   49       1          2        133              142   
3       132514   43       1          0        138              295   
4       146211   31       1          1        199                0   
..         ...  ...     ...        ...        ...              ...   
995    9949544   48       1          2        139              349   
996    9953423   47       1          3        143              258   
997    9965859   69       1          0        156              434   
998    9988507   45       1          1        186              417   
999    9990855   25       1          0        158              270   

     fastingbloodsugar  restingrelectro  maxheartrate  exerciseangia  oldpeak  \
0                    0                1           147              0      5.3 

In [43]:
pip install pydotplus


     ---------------------------------------- 0.0/278.7 kB ? eta -:--:--
     - -------------------------------------- 10.2/278.7 kB ? eta -:--:--
     - -------------------------------------- 10.2/278.7 kB ? eta -:--:--
     ---- -------------------------------- 30.7/278.7 kB 217.9 kB/s eta 0:00:02
     --------- --------------------------- 71.7/278.7 kB 357.2 kB/s eta 0:00:01
     ------------------ ----------------- 143.4/278.7 kB 607.9 kB/s eta 0:00:01
     -------------------------- --------- 204.8/278.7 kB 734.2 kB/s eta 0:00:01
     --------------------------------- -- 256.0/278.7 kB 787.7 kB/s eta 0:00:01
     -----------------------------------  276.5/278.7 kB 741.6 kB/s eta 0:00:01
     ------------------------------------ 278.7/278.7 kB 715.8 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24578 sha256=24382539b2aa858ec87a16ec39

In [47]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import accuracy_score
from io import StringIO
from IPython.display import Image  
import pydotplus

# Preprocessing: Splitting into features and target variable
X = df.drop(columns=['target'])  # Features
y = df['target']  # Target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initializing DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier(random_state=42)

# Training the model
decision_tree_model.fit(X_train, y_train)

# Making predictions
y_pred_train = decision_tree_model.predict(X_train)
y_pred_test = decision_tree_model.predict(X_test)

# Evaluating the model
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

Train Accuracy: 1.0
Test Accuracy: 0.96


In [51]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score

# Preprocessing: Splitting into features and target variable
X = df.drop(columns=['target'])  # Features
y = df['target']  # Target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initializing DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier(random_state=42)

# Training the model
decision_tree_model.fit(X_train, y_train)

# Making predictions
y_pred_train = decision_tree_model.predict(X_train)
y_pred_test = decision_tree_model.predict(X_test)

# Evaluating the model
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

# Getting the text representation of the decision tree
tree_text = export_text(decision_tree_model, feature_names=list(X.columns))
print("Decision Tree:")
print(tree_text)


Train Accuracy: 1.0
Test Accuracy: 0.96
Decision Tree:
|--- slope <= 1.50
|   |--- restingBP <= 159.00
|   |   |--- serumcholestrol <= 467.00
|   |   |   |--- serumcholestrol <= 66.00
|   |   |   |   |--- class: 1
|   |   |   |--- serumcholestrol >  66.00
|   |   |   |   |--- chestpain <= 1.50
|   |   |   |   |   |--- restingrelectro <= 1.50
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- restingrelectro >  1.50
|   |   |   |   |   |   |--- fastingbloodsugar <= 0.50
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- fastingbloodsugar >  0.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- chestpain >  1.50
|   |   |   |   |   |--- restingBP <= 130.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- restingBP >  130.00
|   |   |   |   |   |   |--- age <= 77.50
|   |   |   |   |   |   |   |--- restingBP <= 143.50
|   |   |   |   |   |   |   |   |--- oldpeak <= 0.60
|   |   |   |   |   |   |   |   |   |--- oldpeak <= 0.35
|  